In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [20]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("Vacation_search/Vacation_Search.csv")
vacation_df.head(10)

,City_ID,City,Country,Max Temp,Lat,Lng,Description,Hotel Name
0,2,Rikitea,PF,77.23,-23.1203,-134.9692,scattered clouds,People ThankYou
1,5,Saint-Philippe,RE,74.79,-21.3585,55.7679,scattered clouds,"Chambres d'hôte ""La Trinité"""
2,20,Avarua,CK,82.45,-21.2078,-159.7750,few clouds,Paradise Inn
3,22,Bilaspur,IN,82.76,22.0833,82.1500,scattered clouds,Hotel East Park
4,32,Raub,MY,74.16,3.7899,101.8570,scattered clouds,Daniels Guest House Raub
5,36,Butaritari,KI,81.90,3.0707,172.7902,overcast clouds,Isles Sunset Lodge
6,37,Kapaa,US,82.38,22.0752,-159.3190,light rain,Sheraton Kauai Coconut Beach Resort
7,39,Avera,US,76.55,33.1940,-82.5271,clear sky,NaN
8,42,Vao,NC,73.45,-22.6667,167.4833,overcast clouds,Hotel Kou-Bugny
9,43,Gat,IL,70.39,31.6100,34.7642,clear sky,OlusHome

In [7]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """

<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [13]:
# 4a. Add a marker layer for each city to the map.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [37]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df['City'] == 'Lompoc']
vacation_end = vacation_df.loc[vacation_df['City'] == 'Lompoc']
vacation_stop1 = vacation_df.loc[vacation_df['City'] == 'Oildale']
vacation_stop2 = vacation_df.loc[vacation_df['City'] == 'Enterprise'] 
vacation_stop3 = vacation_df.loc[vacation_df['City'] == 'Saint George'] 
vacation_stop3

,City_ID,City,Country,Max Temp,Lat,Lng,Description,Hotel Name
115,287,Saint George,US,83.62,37.1041,-113.5841,clear sky,Best Western Plus Abbey Inn

In [38]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start.iloc[0,4:6].to_numpy()
end = vacation_end.iloc[0,4:6].to_numpy()
stop1 = vacation_stop1.iloc[0,4:6].to_numpy()
stop2 = vacation_stop2.iloc[0,4:6].to_numpy()
stop3 = vacation_stop3.iloc[0,4:6].to_numpy()

start

array([34.6391, -120.4579], dtype=object)

In [46]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

fig = gmaps.figure(center=(36, -115), zoom_level = 6)
Lompoc = start
Oildale = stop1
Enterprise = stop2
Saint_George = stop3 
roadtrip = gmaps.directions_layer(Lompoc, Lompoc, 
                                  waypoints=[Oildale, Enterprise, Saint_George],
                                  travel_mode="DRIVING")

In [47]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, 
                          vacation_stop2, vacation_stop3]
                         ,ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Lat,Lng,Description,Hotel Name
0,425,Lompoc,US,72.57,34.6391,-120.4579,clear sky,"Holiday Inn Express Lompoc, an IHG Hotel"
1,288,Oildale,US,71.62,35.4197,-119.0195,clear sky,DoubleTree by Hilton Hotel Bakersfield
2,196,Enterprise,US,83.32,36.0252,-115.2419,clear sky,Las Vegas Motorcoach Resort
3,287,Saint George,US,83.62,37.1041,-113.5841,clear sky,Best Western Plus Abbey Inn

In [48]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]


# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [57]:
# 11a. Add a marker layer for each city to the map.
fig=gmaps.figure()
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))